site_name: Mira's Homepage
site_url: https://luelista.net/

theme:
  name: material
  favicon: assets/favicon.png
  features:
    - content.action.edit
    #- navigation.tabs
    - navigation.expand
  palette:
    primary: pink
  icon:
    logo: material/unicorn-variant
  font: false
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - markdown.extensions.md_in_html:
  - admonition
  - pymdownx.details
nav:
  - Home: index.md
  - Blog: blog/index.md
plugins:
  - blog:
      enabled: true
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
  - social:
      cards_layout_options:
        font_family: Bangers

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/luelista/
    - icon: fontawesome/brands/mastodon
      link: https://chaos.social/@luelista

copyright: meow <3   # fuck copyright
