site_name: Mira's Homepage
theme:
  name: material
  features:
    - content.action.edit
  palette:
    primary: pink
  icon:
    logo: material/unicorn-variant
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - markdown.extensions.md_in_html:
nav:
  - Home: index.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/luelista/
    - icon: fontawesome/brands/mastodon
      link: https://chaos.social/@luelista

copyright: Copyright &copy; 2023 Mira Weller
